= Forms

[IMPORTANT]
======
This documentation is up-to-date with React v17. React v18 introduced a new
hook called `useActionState` that makes it much easier to work with forms
in React.
======

Working with native forms forms is one React's weak points.

Traditionally, to dynamically send form data to a server, you would listen to
a form's `submit` event, prevent the default action, capture the values of
all the form's inputs, and send the data to an HTTP endpoint. In React, it
is better practice to dynamically track the state of form inputs, syncing
the values of the inputs with the state of the React components that wrap them
– literally on every keystroke as the user enters data.

This concept is known as *controlled components* in React. It is the
recommended way to work with forms in React.

There are several steps to creating a controlled component. The first step
is to synchronize component state with changes to the values of native form
elements:

[source,jsx]
----
export default function Form() {
  const [formData, setFormData] = React.useState(
    {
      firstName: "",
      lastName: ""
    }
  )

  function handleChange(event) {
    setFormData(prevFormData => {
      return {
        ...prevFormData,
        /* Use ES6 computed property names to turn a dynamic
        string into a key: */
        [event.target.name]: event.target.value
      }
    })
  }

  return (
    <form>
      <input
        type="text"
        placeholder="First Name"
        onChange={handleChange}
        name="firstName"
      />
      <input
        type="text"
        placeholder="Last Name"
        onChange={handleChange}
        name="lastName"
      />
    </form>
  )
}
----

This is good design. We can easily add new inputs to this form by simply syncing
the inputs' `name` attributes with the keys in our state object where we want to
store the associated values.

But these are not yet controlled components. In simple terms, a controlled
component is a React component that renders a form element and controls what
happens in that form on subsequent user input. The idea is that the React
component state should be the single source of truth for _all_ data, including
form data.

At the moment we have two sources of truth: the native form data, and the React
component state.

To fix this, and make the component state the source of truth, it is a simple
matter of setting the `value` attribute of the form inputs to the corresponding
values in the component state:

[source,jsx]
----
export default function Form() {
  const [formData, setFormData] = React.useState(
    {
      firstName: "",
      lastName: ""
    }
  )

  function handleChange(event) {
    setFormData(prevFormData => {
      return {
        ...prevFormData,
        /* Use ES6 computed property names to turn a dynamic
        string into a key: */
        [event.target.name]: event.target.value
      }
    })
  }

  return (
    <form>
      <input
        type="text"
        placeholder="First Name"
        onChange={handleChange}
        name="firstName"
        value={formData.firstName}
      />
      <input
        type="text"
        placeholder="Last Name"
        onChange={handleChange}
        name="lastName"
        value={formData.lastName}
      />
    </form>
  )
}
----

There is no change in the behavior of the form, but conceptually the form is
now "controlled" by the React component. We can mutate the component state
in other ways, and the form rendering will be updated to reflect those changes.

If you don't set this up correctly, React may warn about there existing
uncontrolled components.

HTML forms have other types of input controls, such as radios and checkboxes,
that need some special handling. The following code demonstrates handling of
all the different types of form elements, and also how to handle form
submission:

[source,jsx]
----
export default function Form() {
  const [formData, setFormData] = React.useState(
    {
      firstName: "",
      lastName: "",
      email: "",
      comments: "",
      isFriendly: true,
      employment: "",
      favColor: ""
    }
  )

  /*
  `useId` is another hook that generate a unique ID which we can use for
  our component and its children.
  */
  const id = React.useId()

  function handleChange(event) {
    const {name, value, type, checked} = event.target

    setFormData(prevFormData => {
      return {
        ...prevFormData,
        [name]: type === "checkbox" ? checked : value
      }
    })
  }

  function handleSubmit(event) {
    event.preventDefault()

    // submitToApi(formData)
    console.log(formData)
  }

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor={id + "-firstName"}>First Name</label>
      <input
        type="text"
        onChange={handleChange}
        name="firstName"
        value={formData.firstName}
        id={id + "-firstName"}
      />
      <label htmlFor={id + "-lastName"}>Last Name</label>
      <input
        type="text"
        onChange={handleChange}
        name="lastName"
        value={formData.lastName}
        id={id + "-lastName"}
      />
      <label htmlFor={id + "-email"}>Email</label>
      <input
        type="email"
        onChange={handleChange}
        name="email"
        value={formData.email}
        id={id + "-email"}
      />
      <label htmlFor={id + "-comments"}>Comments</label>
      <textarea
        value={formData.comments}
        onChange={handleChange}
        name="comments"
        id={id + "-comments"}
      />
      <input
        type="checkbox"
        id={id + "-isFriendly"}
        checked={formData.isFriendly}
        onChange={handleChange}
        name="isFriendly"
      />
      <label htmlFor={id + "-isFriendly"}>Are you friendly?</label>
      <br />
      <br />

      <fieldset>
        <legend>Current employment status</legend>
        <input
          type="radio"
          id={id + "-unemployed"}
          name="employment"
          value="unemployed"
          checked={formData.employment === "unemployed"}
          onChange={handleChange}
        />
        <label htmlFor={id + "-unemployed"}>Unemployed</label>
        <br />

        <input
          type="radio"
          id={id + "-part-time"}
          name="employment"
          value="part-time"
          checked={formData.employment === "part-time"}
          onChange={handleChange}
        />
        <label htmlFor={id + "-part-time"}>Part-time</label>
        <br />

        <input
          type="radio"
          id={id + "-full-time"}
          name="employment"
          value="full-time"
          checked={formData.employment === "full-time"}
          onChange={handleChange}
        />
        <label htmlFor={id + "-full-time"}>Full-time</label>
        <br />
      </fieldset>
      <br />

      <label htmlFor={id + "-favColor"}>What is your favorite color?</label>
      <br />
      <select
        id={id + "-favColor"}
        value={formData.favColor}
        onChange={handleChange}
        name="favColor"
      >
        <option value="red">Red</option>
        <option value="orange">Orange</option>
        <option value="yellow">Yellow</option>
        <option value="green">Green</option>
        <option value="blue">Blue</option>
        <option value="indigo">Indigo</option>
        <option value="violet">Violet</option>
      </select>
      <br />
      <br />

      <!-- When a button is in a form, it's default is `type="submit"`. -->
      <button>Submit</button>
    </form>
  )
}
----
