= Environments

Environments are a powerful feature that allow you to configure and manage
deployment targets, such as production, staging, or development. They provide a
way to ensure that your workflows adhere to protection rules and have access to
specific secrets and environment variables.

Environments are used to describe deployment targets. When a workflow deploys to
an environment, the environment's name is displayed on the repository's main
page, making it easy to track deployment history.

Each job in a workflow MAY reference a _single_ environment.

When a workflow job references an environment, it creates a deployment object
with the environment property set to the name of the environment. Deployment
status objects are also created, providing details about the job's progress.
These objects can be accessed via the REST API, GraphQL API, or webhook events.

== Creating and deleting environments

To create an environment, you must have specific permissions based on the
repository's visibility:

* Personal Account Repository: Repository owner can configure environments.
* Organization Repository: Admins can configure environments.

Deleting an environment will remove all associated secrets and protection rules.
Any jobs waiting due to protection rules will fail.

Only repository admins can configure environments, but anyone who can edit
workflows can create environments.

== Protection rules

Protection rules help ensure the security and reliability of your deployments.
There are several protection rule options:

* *Required Reviewers*: You can specify individuals or teams that must approve
  workflow jobs before they can proceed. Only one of the required reviewers
  needs to approve the job for it to proceed.

* *Wait Timer*: Delay a job for a specific amount of time after it is triggered.
  The wait time can be between 0 and 43,200 minutes (30 days).

* *Deployment Branches and Tags*: Restrict which branches and tags can deploy to
  the environment. You can specify patterns for branch and tag names to control
  deployment access.

* *Custom Deployment Protection Rules*: Use third-party services to automate
  approvals and assessments for deployments. You can create custom deployment
  protection rules powered by GitHub Apps.

Any protection rules configured for the environment referenced from a job MUST
pass before the job is sent to a runner. For example, you might configure three
environments:

* Staging
* UAT
* Production

And configure the production environment with the following restrictions:

* Requires 2 reviewers
* Branch restricted to `main` only

The following workflow will run only once it has been approved by two people.

[source,yaml]
----
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        # ...
----

== Environment secrets and variables

Secrets and variables can also be set on a per-environment basis.

Secrets stored in an environment are only available to workflow jobs that
reference the environment. Those secrets will be accessible only after any
environment protection rules pass (ie. after the job has been sent to a runner).

[TIP]
======
Treat environment secrets with the same level of security as repository and
organization secrets.
======

Likewise, variables stores in an environment will be accessible via the `vars`
context, but only in workflow jobs that reference the environment.

