= Events
:toc: macro
:toc-title: Contents

:link-docs-events: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
:link-posix-cron-syntax: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07

toc::[]

== Overview

link:./workflows.adoc[Workflows] are triggered by events. The events that trigger
the execution of a workflow are configured via the `on` attribute in the
workflow's YAML config.

GitHub Actions has 35+ event triggers, which can be broadly divided into three
categories:

* *Repository events*
  ** `push`: triggered when someone pushes to the repository.
  ** `issues`: triggered by a variety of events related to issues.
  ** `pull_request`: triggered by a variety of events related to pull requests.
  ** `pull_request_review`: triggered by a variety of events related to PR
    reviews, eg. submitting, editing, deleting.
  ** `fork`: triggered when a repository is forked.
  ** …

* *Manual triggers*
  ** Triggered via the GitHub UI.
  ** Triggered via the GitHub REST API.
  ** Triggered from another workflow.

* *Scheduled*: Runs as a cron job.

All the possible events that can be used to trigger workflows are
{link-docs-events}[documented here].

You can specify single events like `on: push`, an array of events like
`on: [push, pull_request]`, or an event-configuration map that restricts the
execution of a workflow to specific files, tags, or branch changes.

If you specify multiple events, only one of those events needs to occur to
trigger your workflow. If multiple triggering events for your workflow occur at
the same time, multiple workflow runs will be triggered at the same time (and
run in parallel).

[source,yaml]
----
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  release:
    types: [published, created]
----

== Event filters and action types

Adding event filters and action types allows you to precisely control when
your actions run. Example:

[source,yaml]
----
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release-created events.
  page_build:
  release:
    types: # This configuration does not affect the page_build event above.
      - created
----

In the above example, the `push` and `pull_request` events are configured with
*event filters*, which specify more precise conditions under which the workflow
will be triggered by those events. For these events, the filters are the names
of branches. Other filters available for the `push` event include:

* `branches`
* `branches_ignore`
* `tags`
* `tags_ignore`
* `paths`
* `paths_ignore`

As well as events filters, there are also *activity types*, which are another
way of fine-tuning a workflow's triggers. Types are specified using the `type`
or `types` attributes. If you do not specify the activity types then a workflow
run will be triggered for all the activity types for the event. For example,
the `pull_request` event can be restricted to the following activity types:

* `opened`
* `synchronize` (when a new commit is pushed to the HEAD of the PR)
* `closed`
* `assigned`
* `labeled`
* `edited`
* …

Activity types and event filters can be combined:

[source,yaml]
----
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - 'releases/**'
----

In the above example, the workflow will run whenever a new PR is opened against
the `main` branch or a release branch, or when the PR is subsequently updated
(ie. its HEAD commit is changed, eg. through new commits being pushed).

For some events, it is possible to restrict workflow runs to specific files
or directories that have been modified, using the `paths` filter:

[source,yaml]
----
on:
  push:
    paths:
      - 'src/**'
      - 'docs/'
----

Or when certain tags are pushed:

[source,yaml]
----
on:
  push:
    tags:
      - v*
----

== Scheduled events

The `schedule` attribute allows you to run a workflow on a schedule.

[source,yaml]
----
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "Skip this step on Monday and Wednesday"
      - name: Run every time
        run: echo "Run this step every time"
----

Schedules are defined in UTC times using {link-posix-cron-syntax}[POSIX cron
syntax].

[source,txt]
----
+---------------------- Minute (0-59)
|    +----------------- Hour (0-23)
|    |      +---------- Day of month (1-31)
|    |      |  +------- Month (1-12 or JAN-DEC)
|    |      |  |  +---- Day of week (0-6 or SUN-SAT)
|    |      |  |  |
|    |      |  |  |

*/15 *      *  *  *    # Every 15 minutes
0    3      *  *  SUN  # Every Sunday at 3am
----

== Manual triggers

Workflows can be triggered manually using the GitHub UI, GitHub REST API, or the
GitHub CLI:

[source,sh]
----
gh workflow run greet.yml \
  -f name=mona \
  -f greeting=hello
  -F data=@myfile.txt
----

The workflow MUST be configured to run on the `workflow_dispatch` event. This
is what allows the workflow to be triggered manually, rather than automatically
in response to another system event.

[source,yaml]
----
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        type: string
      greeting:
        description: 'Greeting'
        required: true
        type: string
      data:
        description: 'Base64 encoded content'
        required: false
        type: string
----

== Workflow calls

Workflows can be called from other workflows. This requires the called workflow
to have the `workflow_call` event trigger. See link:./workflows.adoc[workflows]
for more information on workflow calls.

== Webhooks

Many of the listed GitHub workflow triggers are for *webhook events*. A
webhook is a public facing URL – part of the GitHub REST API – that can be
called to trigger events from external sources.

To define webhook events, you use the `repository_dispatch` event. Optionally
you can declare "types", which are like event names that can be subsequently
inputted via the HTTP endpoint.

[source,yaml]
----
on:
  repository_dispatch:
    types: [opened, deleted]
----

For webhook events, you get to choose the activity types that are relevant to
the event – ie. these can be whatever you want them to be.

When you make the request to the webhook you MUST:

* Send a POST request to the repository's `dispatches` endpoint.
* Set the `Accept` type to `application/vnd.github+json`.
* Provide a Personal Access Token via the `Authorization` header.
* Pass the event type, if applicable.

Example using cURL:

[source,sh]
----
curl -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ${{ secrets.MY_PAT }}" \
  -d '{"event_type": "opened", "client_payload": {"key": "value"}}' \
  https://api.github.com/repos/{owner}/{repo}/dispatches
----
