= Expressions

Expressions can be used within workflow files to dynamically evaluate and
manipulate data at runtime, so creating more flexible and intelligent automation.
Expressions are used in various workflow scenarios, such as conditional
statements, setting variables, or generating dynamic content and output.

Expressions are written using the `${{ <expression> }}` syntax.

Expressions can be composed from a combination of:

* Literal values: string, numbers, booleans, null.
* link:./contexts.adoc[Contexts]: values passed via the many workflow contexts.
* link:./functions.adoc[Functions]: built-in functions provided by GitHub Action runners.

Expressions also support operators such as `!`, `<`, `>`, `&&`, `||`, `==`, `!=`,
and many others.

Expressions are perhaps most commonly used to set conditions, in which we use
them to inject values directly into shell conditions, like this:

[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional step using an expression
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "This is a push to the main branch."
          fi
----

We can also use expressions in `if` statements when deciding whether to execute
a step or a job. Under the `if` key, we don't normally need to use the special
`${{ <expression> }}` syntax, because the value of `if` is always evaluated as
an expression.

[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional step using an expression
        if: github.event_name == "push" && github.ref == "refs/heads/main"
        run: echo "This is a push to the main branch."
----

[NOTE]
======
`if` expressions that start with `!` _do_ need to be enclosed in the
`${{ <expression> }}` syntax, because the `!` character is a special character
in YAML.
======

Expressions are most commonly used to reference information from various sources
within the workflow, such as the repository, the runner, or the workflow itself.
This information is made available via workflow contexts – basically, APIs that
are made available by the runner.

.Example: dynamic variable assignment
[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable using an expression
        run: |
          # Define a dynamic variable using an expression
          MY_VAR="Hello, ${{ github.actor }}!"

          # Use the variable in an echo statement
          echo $MY_VAR
----
