= Outputs
:toc: macro
:toc-title: Contents

toc::[]

Outputs are used to pass data generated by one job to a dependent job in the same
workflow.

You use `jobs.<job_id>.outputs` to define outputs for a specific job. Output
values that contain expressions are evaluated at the end of the job's run.

To implement:

1.  Define a step ID for each of the steps that produce output.

2.  Append key-value pairs to the `$GITHUB_OUTPUT` variable.

3.  Mention the outputs in the `outputs` section of the job that generates them.
    This creates a new map of outputs for the whole job, which MAY be generated
    by accessing the `GITHUB_OUTPUT` of individual steps within it.

4.  List the job as a dependency of the jobs that need its output, using the
    `needs` attribute.

5.  Access the output via the `needs` context in the dependent job.

Example:

[source,yaml]
----
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.build.outputs.result }}
    steps:
      - name: Build
        id: build
        run: echo "result=success" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deployment
        env:
          BUILD_STATUS: ${{ needs.build.outputs.result }}
        run: echo "Build Status: $BUILD_STATUS"
----

In this workflow, the "build" job defines an output called `result`,
and the `deploy` job depends on the `build` job. The result is shared from
`build` to `deploy`, allowing you to pass data between these two jobs seamlessly.

[IMPORTANT]
======
Outputs MUST be appended to the $GITHUB_OUTPUT environment variable using
`>>` shell notation. A single `>` will overwrite the file's contents.
======
