= Workflows
:toc: macro
:toc-title: Contents

:link-docs-workflow-syntax: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
:link-example-workflows: https://github.com/actions/starter-workflows

toc::[]

== Overview

A GitHub workflow is a process that you set up in your repository to automate
software development life cycle tasks.

Workflows are scoped to repositories and are configured in YAML files in the
`./.github/workflows` directory of the repository. A repository may have
multiple workflows; each will be configured via a single YAML file.

The {link-docs-workflow-syntax}[workflow syntax is documented here], and GitHub
also has a {link-example-workflows}[repo of example workflows] you can use to
get started.

== Expressions

Expressions can be used within workflow files to dynamically evaluate and
manipulate data at runtime, so creating more flexible and intelligent automation.
Expressions are used in various workflow scenarios, such as conditional
statements, setting variables, or generating dynamic content and output.

Expressions are written using the `${{ <expression> }}` syntax.

Expressions can be composed from a combination of:

* Literal values: string, numbers, booleans, null.
* link:./contexts.adoc[Contexts]: values passed via the many workflow contexts.
* link:./functions.adoc[Functions]: built-in functions provided by GitHub Action runners.

Expressions also support operators such as `!`, `<`, `>`, `&&`, `||`, `==`, `!=`,
and many others.

Expressions are perhaps most commonly used to set conditions, in which we use
them to inject values directly into shell conditions, like this:

[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional step using an expression
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "This is a push to the main branch."
          fi
----

We can also use expressions in `if` statements when deciding whether to execute
a step or a job. Under the `if` key, we don't normally need to use the special
`${{ <expression> }}` syntax, because the value of `if` is always evaluated as
an expression.

[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional step using an expression
        if: github.event_name == "push" && github.ref == "refs/heads/main"
        run: echo "This is a push to the main branch."
----

[NOTE]
======
`if` expressions that start with `!` _do_ need to be enclosed in the
`${{ <expression> }}` syntax, because the `!` character is a special character
in YAML.
======

Expressions are most commonly used to reference information from various sources
within the workflow, such as the repository, the runner, or the workflow itself.
This information is made available via workflow contexts – basically, APIs that
are made available by the runner.

.Example: dynamic variable assignment
[source,yaml]
----
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable using an expression
        run: |
          # Define a dynamic variable using an expression
          MY_VAR="Hello, ${{ github.actor }}!"

          # Use the variable in an echo statement
          echo $MY_VAR
----

== Reusable workflows

A reusable workflow is simply a workflow that can be called from another
workflow. This feature allows you to create modular, shareable workflow
components that can be used across multiple repositories and workflows
within an organization. Often, this is a better solutions to reducing
duplication and complexity in workflows than extracting out to
link:./actions.adoc[actions].

Making a workflow reusable is a simple matter of giving it the `workflow_call`
event trigger. Inputs and secrets may be passed to reusable workflows, and
outputs can be captured from them. These are all specified as properties
of the `workflow_call` event:

.Reusable workflow
[source,yaml]
----
on:
  workflow_call:
    inputs:
      aws-region:
        type: string
    secrets:
      auth-token:
        required: true
    outputs:
      server-url:
        value: <value>
----

Otherwise, reusable workflows are written in the same way as regular workflows.

To call a reusable workflow from a normal workflow, use the `uses` property.
Unlike actions, reusable workflows are called from a job, rather than from
a step. The `with` and `secrets` properties are used to pass inputs and secrets
respectively.

.Caller workflow
[source,yaml]
----
jobs:
  backend-infra-non-prod:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      auth-token: ${{ secrets.GH_PAT }}
----

(This example represents a classic use case for reusable workflows: to deploy to
different environments while ensuring a similar deployment process for all
environments.)

You can also capture outputs from a reusable workflow and use them in the caller
workflow. The process is similar to using outputs between different dependent
jobs in the same workflow, but here you also have to specify the outputs under
the `outputs` keyword in the `workflow_call` event definition, as wells as in
the output from jobs within the reusable workflow. The job passes its outputs
up to the workflow, and then the `workflow_call` event passes them out to the
caller.

.Reusable workflow
[source,yaml]
----
on:
  workflow_call:
    outputs:
      my-output:
        value: ${{ jobs.my-job.outputs.my-output }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    outputs:
      my-output: ${{ steps.my-step.outputs.my-output }}
    steps:
      - name: My step
        id: my-step
        run: |
          # Do something
          echo "my-output=my-value" >> "$GITHUB_OUTPUT"
----

The below example shows how workflows can consume outputs from reusable
workflows. Notice how you need to wait for the job that uses the reusable
workflow to complete before you can access its outputs. You do this in the
normal way: using `needs` to define dependencies between jobs:

.Caller workflow
[source,yaml]
----
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
  use-outputs:
    needs: call-reusable-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.call-reusable-workflow.outputs.my-output }}
----

It is actually possible to nest workflows, so a workflow can call a reusable
workflow which can call a reusable workflow… but only up to four levels of
nesting is supported.

== Workflow templates

Workflow templates are available on Enterprise accounts. They allow you to
create workflows that can be reused across multiple repositories in your
organization. The purpose is to ensure that automation is reused, and used
consistently, across an organization.

Workflow templates are defined in a repository called `.github`, in a
sub-directory called `workflow-templates`. There are two parts to a workflow
template:

1.  Create a YAML workflow file.
2.  Create a JSON metadata file that describes how the template should be
    presented to users when they are creating a workflow.

The metadata file MUST have the same name as the workflow template file. But
instead of the `.y(a)ml` extension, it MUST be appended with `.properties.json`.

.Example workflow template
[source,yaml]
----
name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
----

Notice the `$default-branch` variable. This is a placeholder. When a workflow is
created from this template, this placeholder will be replaced with the name of
the repository's default branch.

.Example metadata file
[source,json]
----
{
    "name": "Octo Organization Workflow",
    "description": "Octo Organization CI workflow template.",
    "iconName": "example-icon",
    "categories": [
        "Go"
    ],
    "filePatterns": [
        "package.json$",
        "^Dockerfile",
        ".*\\.md$"
    ]
}
----

.Metadata file properties
|===
| Parameter | Description | Required?

| `name`
| Name of the workflow template, , shown in the list of available workflow templates.
| Yes

| `description`
| Description, shown in the list of available workflow templates.
| Yes

| `iconName`
| SVG icon name, stored in the `workflow-templates` directory.
| No

| `categories`
| Language categories, for easier search of workflow templates for specific languages.
| No

| `filePatterns`
| Restricts workflows to being created in repositories with matching files in the root directory.
| No
|===

To create a new workflow based on an existing workflow template, go to the
*Actions* tab, select *New workflow*, and then search for the template
under the section titled *Workflows created by <organization name>*.

== Managing concurrency

GiHub Actions' concurrency management feature allows you to control and limit
the number of jobs or workflows that can run simultaneously. This is useful to
prevent job conflicts and resource contention, especially in multi-job workflows.

Concurrency is controlled using the `concurrency` property in your workflow
YAML files. This property is used to define *concurrency groups*. The value of
the `concurrency` property can be any string or expression. When more than one
workflow or job is part of the same concurrency group, only one instance of
that workflow or job will run at a time. If other runs are triggered, those
will be queued to run after the current-running one completes.

It is also possible to cancel any currently running job or workflow in the same
concurrency group using the `cancel-in-progress: true` option. (You will
typically want to disable the `cancel-in-progress` option for deployments.)

[NOTE]
======
* Concurrency group names are case-insensitive.

* Ordering is not guaranteed for jobs or runs using concurrency groups; they
  are handled in the order they are processed.

* Concurrency groups MUST be unique across all workflows, to prevent cancelling
  runs in the wrong workflows.

======

== Disabling workflows

Workflows can be temporarily disabled via the GitHub UI, without having to
delete the workflow configuration file from the default branch.

You can also cancel workflow runs that are in progress, also via the GitHub UI.

''''

== Example workflows

.Publish a new release to GitHub Packages
[source,yaml]
----
name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
----

.Deploy to Azure Web Apps
[source,yaml]
----
jobs:
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    # This prior job will build the Docker image that gets deployed by this job:
    needs: Build-Docker-Image
    name: Deploy app container to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web app container
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
----
