= Custom elements

Web components are composed from three web platform APIs: custom elements, the
shadow DOM, and HTML templates. Each of these APIs may be used independently,
or combined (optionally with other web platform APIs) to create custom,
reusable HTML components.

Custom elements are DOM elements with custom markup, behaviors and content. They
are created using JavaScript APIs and optionally they cna be embedded directly
in HTML documents using normal HTML tags.

Custom elements are distinguished from native HTML elements by having a
namespace, or prefix, in their tag name. The namespace is separated from the
element name with a hyphen. Thus, all custom elements MUST have one or more
hyphens in their name, eg. `<kierans-button>`. By contrast, no native HTML
elements have hyphens in their names, and they never will have, so eliminating
the risk of future name collisions between native and custom elements. (Name
conflicts between custom elements are still possible, however.)

Custom elements are implemented by extending the `HTMLElement` class. To use a
custom element directly in an HTML document, you also need to define a unique
HTML tag name that is associated with the custom element. This second part is
not a requirement of creating a custom element; if a custom element is only
ever injected into the DOM using JavaScript, then there is no need to define
an HTML tag name for it.

.Example
[source,javascript]
====
const template = document.createElement('template');
template.innerHTML = `<p>Hello World</p>`;

class HelloWorld extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.append(template.content.cloneNode(true));
  }
}

customElements.define('hello-world', HelloWorld);
====

The above script does the following:

* It creates a new *template element* and sets its inner HTML.
* It creates a *shadow root* and explicitly sets its mode to "open".
* It clones the template's content and appends it to the shadow root.
* An HTML *tag*, `<hello-world>`, is associated with the custom element,
  allowing embedding of the custom element in HTML markup.
