name: 02 - Workflow Events

# GitHub Actions workflows are triggered by specific events that occur within
# your repository. These triggers define when a workflow should run, automating
# various tasks like continuous integration, testing, and deployment.

on:
  # push:
  # pull_request:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
