name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Settings this in the defaults makes this the default working
        # directory for all steps in this job. It's a bit cleaner than
        # writing `cd <path>` in every step.
        working-directory: _/react-app
    steps:
      # Even though the workflows are defined in the same repository, the
      # workflows run in virtual machines, which do not checkout the
      # code by default. Therefore the "Checkout code" step is required.
      # Since this is a common step, there's a ready-made action for it.
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print directories
        run: ls -la
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        # working-directory: _/react-app (inherited)
      - name: Run unit tests
        # run: |
        #   cd _/react-app
        #   npm run test
        run: npm run test
