name: 07 - Using Expressions

# This shows how to provide a default value when a variable is not available.
# In this case, the debug input would not be available if, for example, the
# workflow was run from a push event.
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

# We could use the same methodology to define defaults for variables,
# just in case they get deleted from the repository or organization secrets.
env:
  MY_ENV_VAR_WITH_DEFAULT: ${{ vars.MY_ENV_VAR || 'default value' }}

on:
  #push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug-mode] Print start-up data'
        if: inputs.debug
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: '[debug-mode] Print when triggered from main'
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: echo "I was triggered from main"
